[build]
  command = "npm install"
  publish = "."
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[context.production]
  environment = { ENVIRONMENT = "production" }
